function init(self)
	self.score = 0
	self.state = 0 -- 0-ready ,1-game, 2-game_over
end

local function change_state(self,state)
	self.state = state
end	

function on_message(self, message_id, message, sender)
	if(message_id == hash("change_state")) then
		change_state(self,message.state)	
	end	
end

function on_input(self, action_id, action)
	if(self.state == 0 and action_id == hash("touch")) then
		change_state(1)	
	end	
end

